export default [
  { "id": 1, "title": "Magia y Hechicería", "icon": "✨" },
  { "id": 2, "title": "Fantasía y Dragones", "icon": "🐉" },
  { "id": 3, "title": "Aventuras Épicas", "icon": "🏹" },
  { "id": 4, "title": "Animales Mágicos", "icon": "🦄" },
  { "id": 5, "title": "Príncipes y Princesas", "icon": "👑" },
  { "id": 6, "title": "Monstruos y Criaturas", "icon": "👾" },
  { "id": 7, "title": "Viajes alucinantes", "icon": "🌌" },
  { "id": 8, "title": "El Misterio y lo Sobrenatural", "icon": "🔮" },
  { "id": 9, "title": "Superhéroes y Superpoderes", "icon": "🦸" },
  { "id": 10, "title": "La Fuerza de la Amistad", "icon": "🤝" },
  { "id": 11, "title": "El Poder de la Imaginación", "icon": "🧠" },
  { "id": 12, "title": "Historias de Navidad Mágicas", "icon": "🎅" },
  { "id": 13, "title": "Aventuras en el Bosque", "icon": "🌳" },
  { "id": 14, "title": "El Granjero y su Granja Mágica", "icon": "🚜" },
  { "id": 15, "title": "Viajes en el Tiempo", "icon": "⏳" },
  { "id": 16, "title": "Historias de los Océanos", "icon": "🌊" },
  { "id": 17, "title": "Las Maravillas del Espacio", "icon": "🌌" },
  { "id": 18, "title": "Leyendas y Mitos", "icon": "📜" },
  { "id": 19, "title": "Los Secretos del Mundo", "icon": "🌍" },
  { "id": 20, "title": "El Maravilloso Mundo de los Robots", "icon": "🤖" },
  { "id": 21, "title": "Superhéroes con Superpoderes Espectaculares", "icon": "🦸‍♂️" },
  { "id": 22, "title": "Historias de los Reyes", "icon": "👑" },
  { "id": 23, "title": "La Importancia del Respeto", "icon": "🙏" },
  { "id": 24, "title": "El Valor de la Compasión", "icon": "❤️" },
  { "id": 25, "title": "Historias de la Naturaleza", "icon": "🌿" },
  { "id": 26, "title": "Aventuras en la Selva", "icon": "🌴" },
  { "id": 27, "title": "El Granjero y sus Animales", "icon": "🐔" },
  { "id": 28, "title": "Los Secretos de las Estrellas", "icon": "⭐" },
  { "id": 29, "title": "Los Viajes de los Inventores", "icon": "🔬" },
  { "id": 30, "title": "El Poder de la Alegría", "icon": "😊" }
]
